alias d='git diff -M'
alias ga='git add -A'
alias gap='ga -p'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gcam='gca --amend'
alias gcl='git fetch --prune && git branch --merged master | grep -v master | xargs git branch -d'
alias gco='git checkout'
alias gl='git log --date-order --pretty="format:%C(yellow)%h%Cblue%d%Creset %s %C(white) %an, %ar%Creset" --graph'
alias gp='git push'
alias gpf='gp --force-with-lease'
alias grh='git reset --hard'
alias gup='git pull'
alias gur='hub pull-request'
alias gupl='gup && gcl'
alias s='git status -sb'
